services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - foot-network

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - foot-network

networks:
  foot-network:
    driver: bridge
